# Generated by Django 5.2 on 2025-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('createDate', models.DateField()),
                ('location', models.CharField()),
                ('bedroomCount', models.IntegerField()),
            ],
        ),
    ]
